# Generated by Django 4.1.5 on 2023-02-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafemenu',
            options={'verbose_name_plural': 'cafe_App'},
        ),
        migrations.AddField(
            model_name='cafemenu',
            name='name',
            field=models.CharField(default='商品名', max_length=255, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='cafemenu',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真'),
        ),
    ]
